// <auto-generated />
namespace BeautyMoldova.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ddb2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ddb2));
        
        string IMigrationMetadata.Id
        {
            get { return "202505081859394_ddb2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
